/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.hoyoung;

import java.util.Locale;
import java.util.TimeZone;
import javax.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@Slf4j
public class RestApplication {

  @PostConstruct
  private void init() {
    Locale.setDefault(Locale.KOREA);
    TimeZone.setDefault(TimeZone.getTimeZone("Asia/Seoul"));
  }

  public static void main(String[] args) {
    SpringApplication.run(RestApplication.class, args);
  }

}